// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Vfp4dE6ZmmWK8P3WHvJG9-ihWhNwE0Y',
    appId: '1:249270361646:web:786a2b8f69874ff9bbc9bf',
    messagingSenderId: '249270361646',
    projectId: 'shopping-list-d4f06',
    authDomain: 'shopping-list-d4f06.firebaseapp.com',
    storageBucket: 'shopping-list-d4f06.appspot.com',
    measurementId: 'G-14RBHVEHMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPauEQaDh9dx6e9MFdDz73rthQAEn_AMc',
    appId: '1:249270361646:android:27382c9c125b2be9bbc9bf',
    messagingSenderId: '249270361646',
    projectId: 'shopping-list-d4f06',
    storageBucket: 'shopping-list-d4f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrN6n5NKg1Fb9rPtjrnRsPnY-0xAVKhL8',
    appId: '1:249270361646:ios:cc816e0cfa12794abbc9bf',
    messagingSenderId: '249270361646',
    projectId: 'shopping-list-d4f06',
    storageBucket: 'shopping-list-d4f06.appspot.com',
    iosClientId: '249270361646-d2t2dgd91fm45fak1328lu2q5a7h3to9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrN6n5NKg1Fb9rPtjrnRsPnY-0xAVKhL8',
    appId: '1:249270361646:ios:cc816e0cfa12794abbc9bf',
    messagingSenderId: '249270361646',
    projectId: 'shopping-list-d4f06',
    storageBucket: 'shopping-list-d4f06.appspot.com',
    iosClientId: '249270361646-d2t2dgd91fm45fak1328lu2q5a7h3to9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
