name: module_product
description: Dart package which manages the product domain.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
